[package]
name = "aoc2021-day5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

[[bin]]
name = "part1"
path = "src/day5-1.rs"

[[bin]]
name = "part2"
path = "src/day5-2.rs"
